// <auto-generated />
using System;
using EShop.Data.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.Data.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20250301110556_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EShop.Entity.Concrete.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0517f36e-53b1-4a0d-b6b3-599afdd926cf",
                            Description = "Yönetici rolü",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "c44cd475-5365-409f-845c-6ea238190b2b",
                            Description = "Normal kullanıcı rolü",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("EShop.Entity.Concrete.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d4757375-a497-496b-85dc-a510027bd9b1",
                            AccessFailedCount = 0,
                            Address = "Ataşehir",
                            City = "İstanbul",
                            ConcurrencyStamp = "788a6915-877a-427f-b2c0-55da9afa78aa",
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adminuser@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ali",
                            Gender = 3,
                            LastName = "Cabbar",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINUSER@GMAIL.COM",
                            NormalizedUserName = "ADMINUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIQOqMddeGYkhBLIxwFuQsSzV949SssTd9Hzvyo6YeJWxVN9683PX9g6DefBlG1rbw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5e5c047-7b4f-418a-811c-5d8217e43f03",
                            TwoFactorEnabled = false,
                            UserName = "adminuser@gmail.com"
                        },
                        new
                        {
                            Id = "d2fe392f-4f60-4963-ba3a-ea52b71fb53e",
                            AccessFailedCount = 0,
                            Address = "Kadıköy",
                            City = "İstanbul",
                            ConcurrencyStamp = "d78d095a-81a2-47a9-93e5-86fd34b568eb",
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "normaluser@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Esin",
                            Gender = 2,
                            LastName = "Çelik",
                            LockoutEnabled = false,
                            NormalizedEmail = "NORMALUSER@GMAIL.COM",
                            NormalizedUserName = "NORMALUSER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELeqHUk31T1/9fSZCIx6DjMmtV4x+DWW7vLM6OyhTpTtXs1GbyjwkF6Rv4Q8mEBXfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f41a89e6-1c51-4eae-badc-fe7658f15ab8",
                            TwoFactorEnabled = false,
                            UserName = "normaluser@gmail.com"
                        });
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "d2fe392f-4f60-4963-ba3a-ea52b71fb53e",
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 662, DateTimeKind.Utc).AddTicks(9528),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationUserId = "d4757375-a497-496b-85dc-a510027bd9b1",
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 662, DateTimeKind.Utc).AddTicks(9535),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EShop.Entity.Concrete.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4505),
                            Description = "Bilgisayarlar, akıllı telefonlar, tabletler, televizyonlar ve diğer tüm elektronik cihazlar bu kategoride bulunabilir. Teknoloji tutkunları için en yeni ve popüler ürünler burada!",
                            ImageUrl = "/images/categories/elektronik.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Elektronik",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4508),
                            Description = "Kadın, erkek ve çocuk giyim ürünleri, ayakkabılar, çantalar ve aksesuarlar bu kategoride. Trendleri yakalayın ve tarzınızı yansıtın!",
                            ImageUrl = "/images/categories/moda.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Moda",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4510),
                            Description = "Ev dekorasyonu, mobilyalar, mutfak gereçleri, bahçe ürünleri ve daha fazlası bu kategoride. Evinizi güzelleştirmek için ihtiyacınız olan her şey burada!",
                            ImageUrl = "/images/categories/ev-yasam.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ev & Yaşam",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4511),
                            Description = "Spor ekipmanları, outdoor giyim, kamp malzemeleri, bisikletler ve fitness ürünleri bu kategoride. Aktif bir yaşam için ihtiyacınız olan her şey burada!",
                            ImageUrl = "/images/categories/spor-outdoor.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor & Outdoor",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4512),
                            Description = "Romanlar, kişisel gelişim kitapları, akademik yayınlar, dergiler ve daha fazlası bu kategoride. Okuma tutkunları için geniş bir seçki!",
                            ImageUrl = "/images/categories/kitap-dergi.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kitap & Dergi",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4541),
                            Description = "Çocuk oyuncakları, yapbozlar, model kitler, hobi malzemeleri ve koleksiyon ürünleri bu kategoride. Hem çocuklar hem de yetişkinler için eğlenceli seçenekler!",
                            ImageUrl = "/images/categories/oyuncak-hobi.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oyuncak & Hobi",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4542),
                            Description = "Cilt bakım ürünleri, makyaj malzemeleri, parfümler, saç bakım ürünleri ve daha fazlası bu kategoride. Kendinizi şımartın ve bakım rutininizi oluşturun!",
                            ImageUrl = "/images/categories/kozmetik-bakim.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kozmetik & Kişisel Bakım",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4543),
                            Description = "Valizler, sırt çantaları, seyahat aksesuarları ve seyahat planlaması için gerekli ürünler bu kategoride. Yeni yerler keşfetmeye hazır olun!",
                            ImageUrl = "/images/categories/seyahat-valiz.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Seyahat & Valiz",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4544),
                            Description = "Bebek giysileri, bebek bakım ürünleri, oyuncaklar, çocuk odası dekorasyonu ve daha fazlası bu kategoride. Bebekler ve çocuklar için en kaliteli ürünler!",
                            ImageUrl = "/images/categories/bebek-cocuk.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bebek & Çocuk",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(4545),
                            Description = "Araç bakım ürünleri, yedek parçalar, araç içi aksesuarlar ve otomotiv ekipmanları bu kategoride. Araç tutkunları için ihtiyaç duyulan her şey!",
                            ImageUrl = "/images/categories/otomotiv.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Otomotiv",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5026),
                            ImageUrl = "/images/products/laptop.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dizüstü Bilgisayar",
                            Price = 1500.00m,
                            Properties = "16GB RAM, 512GB SSD, Intel i7 İşlemci",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5028),
                            ImageUrl = "/images/products/smartphone.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Akıllı Telefon",
                            Price = 800.00m,
                            Properties = "128GB Depolama, 6GB RAM, 5G Desteği",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5031),
                            ImageUrl = "/images/products/tablet.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tablet",
                            Price = 600.00m,
                            Properties = "10.5 inç Ekran, 256GB Depolama, Kalem Desteği",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5032),
                            ImageUrl = "/images/products/smartwatch.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Akıllı Saat",
                            Price = 250.00m,
                            Properties = "GPS, Kalp Atışı Ölçer, Suya Dayanıklı",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5060),
                            ImageUrl = "/images/products/earbuds.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Kablosuz Kulaklık",
                            Price = 150.00m,
                            Properties = "Gürültü Önleyici, 20 Saat Pil Ömrü",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5061),
                            ImageUrl = "/images/products/men-jacket.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Erkek Ceket",
                            Price = 120.00m,
                            Properties = "Slim Fit, Kumaş Ceket",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5062),
                            ImageUrl = "/images/products/women-dress.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kadın Elbise",
                            Price = 80.00m,
                            Properties = "Yazlık Desenli, Pamuklu",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5063),
                            ImageUrl = "/images/products/sneakers.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor Ayakkabı",
                            Price = 90.00m,
                            Properties = "Hafif, Nefes Alabilir Taban",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5064),
                            ImageUrl = "/images/products/bag.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çanta",
                            Price = 70.00m,
                            Properties = "Deri, Günlük Kullanım",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5065),
                            ImageUrl = "/images/products/sunglasses.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Güneş Gözlüğü",
                            Price = 50.00m,
                            Properties = "UV Koruma, Polarize Cam",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5066),
                            ImageUrl = "/images/products/dinner-set.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yemek Takımı",
                            Price = 100.00m,
                            Properties = "12 Parça, Porselen",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5067),
                            ImageUrl = "/images/products/sofa.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kanepe",
                            Price = 500.00m,
                            Properties = "3 Kişilik, Kumaş Kaplama",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5068),
                            ImageUrl = "/images/products/bed-sheet.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yatak Örtüsü",
                            Price = 60.00m,
                            Properties = "Pamuklu, 200x220 cm",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5069),
                            ImageUrl = "/images/products/lamp.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Masa Lambası",
                            Price = 40.00m,
                            Properties = "LED, Ayarlanabilir Işık",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5070),
                            ImageUrl = "/images/products/vacuum.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Süpürge",
                            Price = 120.00m,
                            Properties = "Elektrikli, HEPA Filtre",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5071),
                            ImageUrl = "/images/products/gym-bag.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor Çantası",
                            Price = 45.00m,
                            Properties = "30 Litre, Çok Bölmeli",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5072),
                            ImageUrl = "/images/products/tent.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tent",
                            Price = 200.00m,
                            Properties = "4 Kişilik, Su Geçirmez",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5073),
                            ImageUrl = "/images/products/bike.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bisiklet",
                            Price = 350.00m,
                            Properties = "21 Vites, Dağ Bisikleti",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5075),
                            ImageUrl = "/images/products/treadmill.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Koşu Bandı",
                            Price = 600.00m,
                            Properties = "Katlanabilir, 12 Program",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5076),
                            ImageUrl = "/images/products/gloves.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Spor Eldiveni",
                            Price = 25.00m,
                            Properties = "Antrenman için, Ergonomik",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5077),
                            ImageUrl = "/images/products/novel.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Roman Kitabı",
                            Price = 20.00m,
                            Properties = "En Çok Satanlar Listesinden",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5078),
                            ImageUrl = "/images/products/self-help.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kişisel Gelişim Kitabı",
                            Price = 25.00m,
                            Properties = "Motivasyon ve Başarı İçin",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5079),
                            ImageUrl = "/images/products/sci-fi.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bilim Kurgu Kitabı",
                            Price = 30.00m,
                            Properties = "Klasik Bilim Kurgu Eseri",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5080),
                            ImageUrl = "/images/products/magazine.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dergi",
                            Price = 10.00m,
                            Properties = "Aylık Teknoloji Dergisi",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5081),
                            ImageUrl = "/images/products/kids-book.png",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Çocuk Kitabı",
                            Price = 15.00m,
                            Properties = "Resimli, Eğitici Hikayeler",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5082),
                            ImageUrl = "/images/products/lego.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Lego Seti",
                            Price = 80.00m,
                            Properties = "1000 Parça, Yaratıcı Set",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5083),
                            ImageUrl = "/images/products/model-plane.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Model Uçak",
                            Price = 50.00m,
                            Properties = "1:100 Ölçekli, Detaylı",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5084),
                            ImageUrl = "/images/products/puzzle.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Puzzle",
                            Price = 30.00m,
                            Properties = "1000 Parça, Manzara Temalı",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5085),
                            ImageUrl = "/images/products/coloring-book.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Boyama Kitabı",
                            Price = 20.00m,
                            Properties = "Yetişkinler İçin Mandala",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5086),
                            ImageUrl = "/images/products/rc-car.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "RC Araba",
                            Price = 70.00m,
                            Properties = "Uzaktan Kumandalı, Hızlı",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5087),
                            ImageUrl = "/images/products/moisturizer.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nemlendirici Krem",
                            Price = 40.00m,
                            Properties = "Cilt Bariyerini Güçlendirir",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5088),
                            ImageUrl = "/images/products/lipstick.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ruj",
                            Price = 25.00m,
                            Properties = "Uzun Süre Kalıcı, 12 Renk Seçeneği",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5089),
                            ImageUrl = "/images/products/perfume.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Parfüm",
                            Price = 60.00m,
                            Properties = "100 ml, Günlük Kullanım",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5090),
                            ImageUrl = "/images/products/shampoo.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Şampuan",
                            Price = 15.00m,
                            Properties = "Saç Dökülmesine Karşı Etkili",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5091),
                            ImageUrl = "/images/products/razor.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tıraş Makinesi",
                            Price = 90.00m,
                            Properties = "Islak & Kuru Kullanım",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5092),
                            ImageUrl = "/images/products/diapers.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bebek Bezi",
                            Price = 40.00m,
                            Properties = "Hipoalerjenik, 120 Adet",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5092),
                            ImageUrl = "/images/products/stroller.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bebek Arabası",
                            Price = 200.00m,
                            Properties = "Katlanabilir, Hafif",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5093),
                            ImageUrl = "/images/products/doll.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Oyuncak Bebek",
                            Price = 35.00m,
                            Properties = "Gerçekçi Tasarım, 30 cm",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5094),
                            ImageUrl = "/images/products/kids-bike.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Bisikleti",
                            Price = 100.00m,
                            Properties = "12 inç, Yardımcı Tekerlekli",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreateDate = new DateTime(2025, 3, 1, 11, 5, 55, 579, DateTimeKind.Utc).AddTicks(5095),
                            ImageUrl = "/images/products/baby-clothes.png",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bebek Giysisi",
                            Price = 20.00m,
                            Properties = "Pamuklu, Rahat",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EShop.Entity.Concrete.ProductCategory", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 4
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 5
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 6
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 7
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 9
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d4757375-a497-496b-85dc-a510027bd9b1",
                            RoleId = "0517f36e-53b1-4a0d-b6b3-599afdd926cf"
                        },
                        new
                        {
                            UserId = "d2fe392f-4f60-4963-ba3a-ea52b71fb53e",
                            RoleId = "c44cd475-5365-409f-845c-6ea238190b2b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Cart", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.CartItem", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Order", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.OrderItem", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Entity.Concrete.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.ProductCategory", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Entity.Concrete.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EShop.Entity.Concrete.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Category", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Entity.Concrete.Product", b =>
                {
                    b.Navigation("ProductCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
